"""Local infographic generation for notification channels."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Iterable

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:  # pragma: no cover - exercised only when dependency is missing
    Image = None
    ImageDraw = None
    ImageFont = None


def _font(size: int):
    candidates = [
        "C:/Windows/Fonts/msyh.ttc",
        "C:/Windows/Fonts/simhei.ttf",
        "C:/Windows/Fonts/simsun.ttc",
        "/usr/share/fonts/truetype/wqy/wqy-microhei.ttc",
        "/System/Library/Fonts/PingFang.ttc",
    ]
    for candidate in candidates:
        path = Path(candidate)
        if path.exists():
            try:
                return ImageFont.truetype(str(path), size)
            except OSError:
                continue
    return ImageFont.load_default()


def _wrap(draw: ImageDraw.ImageDraw, text: str, font, max_width: int) -> list[str]:
    lines: list[str] = []
    current = ""
    for char in text:
        probe = current + char
        width = draw.textbbox((0, 0), probe, font=font)[2]
        if width <= max_width:
            current = probe
            continue
        if current:
            lines.append(current)
        current = char
    if current:
        lines.append(current)
    return lines


def _pick_category(tags: Iterable[str]) -> str:
    lowered = {tag.lower() for tag in tags}
    if {"gpu", "cuda", "chip", "hardware", "inference"} & lowered:
        return "Infrastructure"
    if {"security", "safety", "policy"} & lowered:
        return "Risk"
    if {"agent", "langchain", "langgraph", "tooling"} & lowered:
        return "Agents"
    if {"openai", "anthropic", "google", "meta"} & lowered:
        return "Vendors"
    return "AI Update"


def generate_news_infographic(item, output_dir: str) -> str:
    if Image is None or ImageDraw is None or ImageFont is None:
        raise RuntimeError("Feishu infographic requires the optional dependency 'Pillow'")

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    width, height = 1200, 675
    image = Image.new("RGB", (width, height), (244, 247, 251))
    draw = ImageDraw.Draw(image)

    navy = (15, 38, 68)
    blue = (38, 99, 235)
    orange = (234, 88, 12)
    slate = (51, 65, 85)
    light = (226, 232, 240)

    draw.rectangle([0, 0, width, 12], fill=blue)
    draw.rounded_rectangle([60, 60, width - 60, height - 60], radius=28, fill=(255, 255, 255))
    draw.rounded_rectangle([70, 70, 360, 125], radius=18, fill=(239, 246, 255))

    title_font = _font(42)
    body_font = _font(28)
    meta_font = _font(22)
    tag_font = _font(24)

    category = _pick_category(item.tags)
    draw.text((92, 84), category, fill=blue, font=tag_font)
    draw.text((880, 86), datetime.now().strftime("%Y-%m-%d"), fill=orange, font=tag_font)

    title_lines = _wrap(draw, item.title[:110], title_font, width - 180)
    title_y = 155
    for line in title_lines[:3]:
        draw.text((90, title_y), line, fill=navy, font=title_font)
        title_y += 54

    draw.line([90, title_y + 12, width - 90, title_y + 12], fill=light, width=3)

    summary = item.ai_summary or item.summary or item.title
    summary_lines = _wrap(draw, summary[:240], body_font, width - 180)
    body_y = title_y + 42
    for line in summary_lines[:6]:
        draw.text((90, body_y), line, fill=slate, font=body_font)
        body_y += 38

    tag_text = " | ".join(item.tags[:4]) if item.tags else item.source
    draw.text((90, height - 130), f"Source: {item.source}", fill=blue, font=meta_font)
    draw.text((90, height - 95), f"Score: {item.score:.0f}   Tags: {tag_text}", fill=slate, font=meta_font)
    draw.text((90, height - 60), "Generated by ai-intake", fill=orange, font=meta_font)

    filename = f"infographic_{datetime.now().strftime('%Y%m%d_%H%M%S')}.jpg"
    target = output_path / filename
    image.save(target, "JPEG", quality=94)
    return str(target)
